### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by samselikoff** [ember-launch-darkly/ember-launch-darkly#29]
Hello there! Thanks for this great addon 😄 

We think we've identified a memory leak coming from this addon. We ran a unit test that didn't even boot the Ember app and noticed a dangling reference to `container`. When we uninstalled this addon, the reference went away.

So that tells me it might be something either in `index.js`, or in one of the initializers (if they even get run in the unit test).

Just wanted to open this to ask if this is known, and/or if we start diving in to fix it, is someone watching the repo who will be able to get this fix merged.

Thanks!

**Comment by patcoll** [comment]
Hey Sam, not known to me but I’m sure we can help merge a fix.

**Comment by achambers** [comment]
Hey @samselikoff . Thanks for the heads up dude. I'm in the process of updating this addon (which is taking waaaaay longer than I'd hope due to...well....tme)  to latest ember and LD client. I may very well have inadvertently fixed this memory leak as I've done some work around the initializers. But would love to hear more from you about this.

Worth a catch up soon?

**Comment by achambers** [comment]
@samselikoff Do you have a repo that reproduces this that I can pull down to do some digging?

**Comment by samselikoff** [comment]
Sorry for leaving you hanging - I'll close this for now until/when we have a repro. Thanks!

**Comment by achambers** [comment]
No probs @samselikoff . I've got an idea what _might_ be causing this so I'm super interested to understand more. Hit me up when you have a chance to repro it and we'll try and get to the bottom of it.
